# Generated by Django 5.0.6 on 2024-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=35)),
                ('image', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('review', models.TextField(max_length=100)),
            ],
        ),
    ]
